name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js and Build
        run: |
          cd frontend
          npm install
          npm run build

      - name: Deploy built files to server with rsync
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # rsync ist sicherer und effizienter als rm+scp
            # -a: Archivmodus (erhält Rechte, etc.)
            # -v: Verbose (zeigt, was es tut)
            # -z: Komprimiert die Daten beim Übertragen
            # --delete: Löscht Dateien im Ziel, die in der Quelle nicht mehr existieren
            rsync -avz --delete frontend/dist/ /docker/sites/eppelstyle.de/www/

      - name: Purge Cloudflare Cache
        if: success()
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data '{"purge_everything":true}'
