name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js and Build
        run: |
          cd frontend
          npm install
          npm run build

      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTH_KEY }}

      - name: Deploy built files to server with rsync
        uses: appleboy/ssh-action@v1.0.3
        with:
          # WICHTIGE ÄNDERUNG: Wir benutzen die Tailscale-IP deines Servers!
          host: 100.98.192.86
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rsync -avz --delete frontend/dist/ /docker/sites/eppelstyle.de/www/

      - name: Purge Cloudflare Cache
        if: success()
        # Läuft ebenfalls über die sichere Tailscale-Verbindung
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 100.98.192.86
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data '{"purge_everything":true}'
